# Generated by Django 4.2.23 on 2025-09-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Paket C Setara SMA', max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal_pendaftaran', models.DateTimeField(auto_now_add=True)),
                ('program_pilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkbmapp.program')),
            ],
        ),
    ]
