# Generated by Django 4.2.23 on 2025-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkbmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('bulan', models.CharField(blank=True, choices=[('01', 'Januari'), ('02', 'Februari'), ('03', 'Maret'), ('04', 'April'), ('05', 'Mei'), ('06', 'Juni'), ('07', 'Juli'), ('08', 'Agustus'), ('09', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], max_length=2)),
            ],
        ),
    ]
