# Generated by Django 4.2.23 on 2025-10-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkbmapp', '0002_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('kategori', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(upload_to='berita/')),
                ('penulis', models.CharField(default='Admin', max_length=100)),
                ('tanggal_publikasi', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_publikasi'],
            },
        ),
    ]
