# Generated by Django 4.2.23 on 2025-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkbmapp', '0003_berita'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video lokal (mp4/mov)', null=True, upload_to='galeri/video/'),
        ),
        migrations.AddField(
            model_name='galeri',
            name='video_url',
            field=models.URLField(blank=True, help_text='Masukkan URL video Facebook atau YouTube (opsional)', null=True),
        ),
    ]
