# Generated by Django 4.2.25 on 2025-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkbmapp', '0004_galeri_video_file_galeri_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasukanSaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=150)),
                ('pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
