# Generated by Django 4.2.25 on 2025-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkbmapp', '0006_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='galeri/'),
        ),
    ]
