# Generated by Django 4.2.23 on 2025-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sekolah_asal', models.CharField(max_length=100)),
                ('program_pilihan', models.CharField(choices=[('paket_a', 'Paket A (SD Sederajat)'), ('paket_b', 'Paket B (SMP Sederajat)'), ('paket_c', 'Paket C (SMA Sederajat)')], max_length=20)),
                ('foto_diri', models.ImageField(upload_to='pendaftaran/foto_diri/')),
                ('fotocopy_ijazah', models.FileField(upload_to='pendaftaran/ijazah/')),
                ('kartu_keluarga', models.FileField(upload_to='pendaftaran/kk/')),
                ('bukti_pembayaran', models.FileField(upload_to='pendaftaran/bukti/')),
                ('rapor_sekolah', models.FileField(upload_to='pendaftaran/rapor/')),
                ('surat_keterangan_sekolah', models.FileField(upload_to='pendaftaran/surat/')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
